apiVersion: apps/v1
kind: Deployment
metadata:
  name: texteditor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: texteditor
  template:
    metadata:
      labels:
        app: texteditor
    spec:
      containers:
      - name: texteditorcontainer
        image: nigachu42/text-editor:latest
        ports:
        - containerPort: 3000
